{
    "tools": {
        "php_mess_detector": {
            "enabled": true,
            "extensions": {
                "0": "php"
            },
            "command": "phpmd",
            "filter": {
                "paths": {

                },
                "excluded_paths": {

                }
            },
            "config": {
                "rulesets": {
                    "0": "codesize"
                }
            },
            "path_configs": {

            }
        },
        "php_cs_fixer": {
            "enabled": true,
            "extensions": {
                "0": "php"
            },
            "command": "php-cs-fixer",
            "filter": {
                "paths": {

                },
                "excluded_paths": {

                }
            },
            "config": {
                "level": "psr1",
                "fixers": {

                }
            },
            "path_configs": {

            }
        },
        "php_analyzer": {
            "enabled": true,
            "filter": {
                "excluded_paths": {
                    "0": "*\/Tests\/*"
                },
                "paths": {

                }
            },
            "extensions": {
                "0": "php"
            },
            "path_configs": {

            }
        },
        "php_code_sniffer": {
            "enabled": true,
            "config": {
                "standard": "PSR1",
                "sniffs": {

                },
                "config": {

                }
            },
            "extensions": {
                "0": "php"
            },
            "command": "phpcs",
            "filter": {
                "paths": {

                },
                "excluded_paths": {

                }
            },
            "path_configs": {

            }
        },
        "sensiolabs_security_checker": {
            "enabled": true,
            "filter": {
                "paths": {

                },
                "excluded_paths": {

                }
            }
        }
    },
    "filter": {
        "paths": {

        },
        "excluded_paths": {

        }
    },
    "before_commands": {

    },
    "after_commands": {

    },
    "artifacts": {

    }
}
