language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before-script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml --coverage-text
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after-script:
  - php vendor/bin/coveralls
